version: '2.3'
services:
  radameon:
    environment:
      - OPER_HOME=/home/radameon
      - HUID
      - HGID
      - DISPLAY
      - QT_X11_NO_MITSHM=1

    image: "radameon/${_image_name}:${_image_tag}"
    container_name: radameon_dev

    # --it 
    stdin_open: true
    tty: true

    # mount volumes
    volumes:
      # mount root source dir
      - "${_source_dir_host}:${_source_dir_target}"

      # caches 
      - ~/.cache/bazel:/bazel

      # file exchange
      - ~/exchange:/exchange

      # clion and .ssh
      - ./additional:/home/radameon/additional

      # x11
      - /tmp/.X11-unix:/tmp/.X11-unix