version: '2.3'
services:
  radameon_dev:
    extends:
      file: radameon.yaml
      service: radameon

    container_name: radameon_dev

    volumes:
      # tools
      - type: bind
        source: $HOME/.gitconfig
        target: /home/oper/.gitconfig

      - /var/run/docker.sock:/var/run/docker.sock

    network_mode: "host"
    privileged: true

    command: ["/entrypoint.sh"]
