# This is a replace for run_docker.sh
version: '2.3'
services:
  rcbe_dev:
    extends:
      file: rcbe.yaml
      service: rcbe

    container_name: rcbe_dev

    volumes:
      # tools
      - type: bind
        source: $HOME/.gitconfig
        target: /home/oper/.gitconfig

      - /var/run/docker.sock:/var/run/docker.sock

    network_mode: "host"
    privileged: true

    command: ["/entrypoint.sh"]
