cc_library(
    name = "rcbe_exception",
    hdrs = glob([
        "include/rcbe_exceptions/**/*.hpp",
    ]),
    include_prefix = "rcbe-engine/exceptions",
    includes = ["include/rcbe_exceptions"],
    strip_include_prefix = "include/rcbe_exceptions",
    visibility = ["//visibility:public"],
    deps = [],
)
