#cc_library(
#    name = "engine_gui",
#    srcs = glob([
#        "src/**/*.cpp",
#    ],
#    exclude = ["src/main.cpp"]),
#    hdrs = glob([
#        "include/**/*.hpp",
#        "include/**/*.h",
#    ]),
#    includes = ["include"],
#    visibility = ["//visibility:public"],
#    deps = [
#        "//thirdparty/nlohmann:nlohmann",
#        "//engine_datamodel:engine_datamodel",
#        #"@gtkmm",
#        "@boost//:filesystem",
#        "@boost//:program_options",
#    ],
#)

#cc_binary(
#    name = "rcbe_engine",
#    srcs = ["src/main.cpp"],
#    deps = [":engine_gui"],
#    visibility = ["//visibility:public"],
#)