cc_library(
    name = "engine_filesystem_utils",
    hdrs = glob([
        "include/common/utils/file_utils.h",
    ]),
    srcs = glob([
        "src/common/utils/file_utils.cpp",
    ]),
    includes = ["include"],
    linkopts = ["-lpthread"],
    visibility = ["//visibility:public"]
)