cc_binary(
    srcs = glob(["src/**/*.cpp"]),
    name = "bazel_test",
    deps = [
        "@boost//:program_options",
        "@boost//:filesystem",
    ],
    visibility = ["//visibility:public"]
)