cc_library(
    name = "engine_datamodel",
    srcs = glob([
            "src/**/*.cpp",
    ]),
    hdrs = glob([
        "include/**/*.hpp",
        "include/**/*.h",
    ]),
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//engine_common:engine_common",
    ], 
)