cc_library(
    name = "rcbe_traits",
    hdrs = glob(["include/**/*.hpp"]),
    include_prefix = "rcbe",
    includes = ["include"],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = [],
)
