cc_library(
    name = "gl_extensions",
    srcs = glob(
        ["src/gl_extensions.cpp"],
        exclude = ["src/main.cpp"],
    ),
    hdrs = glob(["include/core/gl_extensions.hpp"]),
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [],
)
