name: Docker build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ created ]
    branches: [ master ]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: radameon/build:latest
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 2
    steps:
      - uses: actions/checkout@v2
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Print bazel version
        run: bazel --version
      - name: Which clang
        run: which clang-14
      - name: Which gcc
        run: which gcc-12
